function [hPatch,hPlot] = fillSEMplot(x,y,SEM,colorY,colorSEM,ax)
if nargin==5
    ax = gca;
end

hPatch = fill(ax,[x';flipud(x')],...
    [y'-SEM';flipud(y'+SEM')],...
    colorSEM,'FaceAlpha','0.6',...
    'linestyle','none','HandleVisibility','off');
hold(ax,'on')
hPlot = plot(ax,x,y,'LineWidth',3,...
    'Color',colorY);